//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetallicBlueDev.EntityGateCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetallicBlueDev.EntityGateCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply entity tracking....
        /// </summary>
        internal static string ApplyEntityTracking {
            get {
                return ResourceManager.GetString("ApplyEntityTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the entity &apos;{0}&apos; to the state &apos;{1}&apos;..
        /// </summary>
        internal static string ChangeEntityToState {
            get {
                return ResourceManager.GetString("ChangeEntityToState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration has been changed..
        /// </summary>
        internal static string ConfigurationChanged {
            get {
                return ResourceManager.GetString("ConfigurationChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration &apos;{0}&apos; has been loaded..
        /// </summary>
        internal static string ConfigurationHasBeenLoaded {
            get {
                return ResourceManager.GetString("ConfigurationHasBeenLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration is synchronized with the context..
        /// </summary>
        internal static string ConfigurationSynchronized {
            get {
                return ResourceManager.GetString("ConfigurationSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection name &apos;{0}&apos; is invalid or &apos;ConnectionStrings&apos; is corrupt..
        /// </summary>
        internal static string ConnectionStringIsInvalid {
            get {
                return ResourceManager.GetString("ConnectionStringIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ConnectionString found for connection name &apos;{0}&apos;..
        /// </summary>
        internal static string ConnectionStringNotFound {
            get {
                return ResourceManager.GetString("ConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context options extension must be defined..
        /// </summary>
        internal static string ContextOptionsExtensionUndefined {
            get {
                return ResourceManager.GetString("ContextOptionsExtensionUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current entity type is &apos;{0}&apos;..
        /// </summary>
        internal static string CurrentEntityTypeState {
            get {
                return ResourceManager.GetString("CurrentEntityTypeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting &apos;{0}&apos; &apos;{1}&apos;..
        /// </summary>
        internal static string DeletingEntity {
            get {
                return ResourceManager.GetString("DeletingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection of changes..
        /// </summary>
        internal static string DetectionOfChanges {
            get {
                return ResourceManager.GetString("DetectionOfChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity key not found for entity &apos;{0}&apos; (&apos;{1}&apos;)..
        /// </summary>
        internal static string EntityKeyNotFound {
            get {
                return ResourceManager.GetString("EntityKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type &apos;{0}&apos; is not serializable..
        /// </summary>
        internal static string EntityTypeIsNotSerializable {
            get {
                return ResourceManager.GetString("EntityTypeIsNotSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current entity type is undefined..
        /// </summary>
        internal static string EntityTypeUndefined {
            get {
                return ResourceManager.GetString("EntityTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create context with entity type &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToCreateContextWithEntityType {
            get {
                return ResourceManager.GetString("FailedToCreateContextWithEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create context with type &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToCreateContextWithType {
            get {
                return ResourceManager.GetString("FailedToCreateContextWithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute command &apos;{0}&apos; for entity &apos;{1}&apos; (&apos;{2}&apos;)..
        /// </summary>
        internal static string FailedToExecuteCommand {
            get {
                return ResourceManager.GetString("FailedToExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to track POCO entities..
        /// </summary>
        internal static string FailedToTrackPocoEntities {
            get {
                return ResourceManager.GetString("FailedToTrackPocoEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing context....
        /// </summary>
        internal static string InitializingContext {
            get {
                return ResourceManager.GetString("InitializingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration..
        /// </summary>
        internal static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid context..
        /// </summary>
        internal static string InvalidContext {
            get {
                return ResourceManager.GetString("InvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity..
        /// </summary>
        internal static string InvalidEntity {
            get {
                return ResourceManager.GetString("InvalidEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity entry for &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidEntityEntryFor {
            get {
                return ResourceManager.GetString("InvalidEntityEntryFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity for refresh changes..
        /// </summary>
        internal static string InvalidEntityRefreshChanges {
            get {
                return ResourceManager.GetString("InvalidEntityRefreshChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State &apos;{0}&apos; is not valid entity state for tracking ({1})..
        /// </summary>
        internal static string InvalidEntityStateForTracking {
            get {
                return ResourceManager.GetString("InvalidEntityStateForTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity type &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidEntityType {
            get {
                return ResourceManager.GetString("InvalidEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid main entity..
        /// </summary>
        internal static string InvalidMainEntity {
            get {
                return ResourceManager.GetString("InvalidMainEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lazy loading is &apos;{0}&apos;..
        /// </summary>
        internal static string LazyLoadingState {
            get {
                return ResourceManager.GetString("LazyLoadingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List entity &apos;{0}&apos; (&apos;{1}&apos;)..
        /// </summary>
        internal static string ListEntity {
            get {
                return ResourceManager.GetString("ListEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading entity &apos;{0}&apos; (&apos;{1}&apos;)..
        /// </summary>
        internal static string LoadingEntity {
            get {
                return ResourceManager.GetString("LoadingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making a new context....
        /// </summary>
        internal static string MakingNewContext {
            get {
                return ResourceManager.GetString("MakingNewContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must implement the interface &apos;{1}&apos;..
        /// </summary>
        internal static string MustImplementInterface {
            get {
                return ResourceManager.GetString("MustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New attempt ({1}/{2}: {3} seconds)..
        /// </summary>
        internal static string NewAttempt {
            get {
                return ResourceManager.GetString("NewAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no tracked entity..
        /// </summary>
        internal static string NoTrackedEntity {
            get {
                return ResourceManager.GetString("NoTrackedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources are no longer available..
        /// </summary>
        internal static string ObjectDisposed {
            get {
                return ResourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object state entry not found for {0}..
        /// </summary>
        internal static string ObjectStateEntryNotFound {
            get {
                return ResourceManager.GetString("ObjectStateEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query: &apos;{0}&apos;..
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes..
        /// </summary>
        internal static string SavingChanges {
            get {
                return ResourceManager.GetString("SavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving &apos;{0}&apos; &apos;{1}&apos; in state &apos;{2}&apos;..
        /// </summary>
        internal static string SavingEntityInState {
            get {
                return ResourceManager.GetString("SavingEntityInState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create object &apos;{0}&apos; with type &apos;{1}&apos;..
        /// </summary>
        internal static string UnableToCreateObject {
            get {
                return ResourceManager.GetString("UnableToCreateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the type &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToCreateType {
            get {
                return ResourceManager.GetString("UnableToCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute {0} command after {1} retry..
        /// </summary>
        internal static string UnableToExecuteCommand {
            get {
                return ResourceManager.GetString("UnableToExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute the request: &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToExecuteRequest {
            get {
                return ResourceManager.GetString("UnableToExecuteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find ConnectionString &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToFindConnectionString {
            get {
                return ResourceManager.GetString("UnableToFindConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get property name &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToGetPropertyName {
            get {
                return ResourceManager.GetString("UnableToGetPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to handle this entity type..
        /// </summary>
        internal static string UnableToHandleEntityType {
            get {
                return ResourceManager.GetString("UnableToHandleEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load {0} with identifier &apos;{1}&apos;..
        /// </summary>
        internal static string UnableToLoadEntityKey {
            get {
                return ResourceManager.GetString("UnableToLoadEntityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain all the information contained in the entity &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToObtainInformationContainedInEntity {
            get {
                return ResourceManager.GetString("UnableToObtainInformationContainedInEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected entity state &apos;{0}&apos; for &apos;{1}&apos;..
        /// </summary>
        internal static string UnexpectedEntityState {
            get {
                return ResourceManager.GetString("UnexpectedEntityState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown query..
        /// </summary>
        internal static string UnknownQuery {
            get {
                return ResourceManager.GetString("UnknownQuery", resourceCulture);
            }
        }
    }
}
